# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Can I? - HackHerThon' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Can I? - HackHerThon

pod 'FSCalendar'

end
